accueil_login/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^deconnexion$', views.deconnexion, name='deconnexion'),
    url(r'^hello/$', views.hello, name='hello'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
	url(r'^apropos/$', views.apropos, name='apropos'),
]

importationfichier/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from importationfichier import views

app_name = 'importefichier'
urlpatterns = [
	url(r'^upload$', views.upload, name='upload'),
	url(r'^nouveau_document$', views.nouveau_document, name='nouveau_document'),
	url(r'^import_bdd$', views.import_bdd, name='import_bdd'),
	url(r'^import_bdd/(\d+)$',views.upload_bdd,name='upload_bdd'),
	url(r'^delete_file/(\d+)$',views.delete_file,name='delete_file'),
	url(r'^delete_base_eleve$',views.delete_base_eleve,name='delete_base_eleve'),
	url(r'^delete_base_stage$',views.delete_base_stage,name='delete_base_stage'),
	url(r'^delete_base_programme$',views.delete_base_programme,name='delete_base_programme'),

]

profil/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from profil import views

app_name = 'profil'
urlpatterns = [
	url(r'^user_profil$', views.user_profil, name='user_profil'),
	url(r'^editprofil$',views.user_profil, name="editprofil"),
	url(r'^pageprofil$', views.pageprofil, name='pageprofil'),

]

statistiques/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from statistiques import views

app_name = 'statistiques'
urlpatterns = [
	url(r'^menu_stats$', views.menu_stats, name='menu_stats'),
	url(r'^uni_programme$', views.uni_programme, name='uni_programme'),
	url(r'^quali_quali$',views.quali_quali, name ='quali_quali'),
	url(r'^uni_eleves$',views.uni_eleves, name ='uni_eleves'),
	url(r'^result$',views.result, name ='result'),
	url(r'^money_stage$',views.money_stage, name ='money_stage'),
	url(r'^best_stage$',views.best_stage, name ='best_stage'),

]

stats/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
	path('nous_contacter/', include('nous_contacter.urls')),
    path('accueil_login/', include('accueil_login.urls')),
    #path('importationfichier/', include('importationfichier.urls')),
    path('backoffice/', include('backoffice.urls')),
    path('admin/', admin.site.urls),
    path('statistiques/', include('statistiques.urls')),
    path('importationfichier/', include('importationfichier.urls',namespace='importationfichier')),
	path('profil/', include('profil.urls')),
]

accueil_login/models.py
from django.db import models

# Create your models here.

accueil_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

        
class ConnexionForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", max_length=30)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)

accueil_login/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import SignupForm, ConnexionForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.urls import reverse
from django.contrib.auth.decorators import login_required



def home(request):
	error = False

	if request.method == "POST":
		print("okokokoko")
		form = ConnexionForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data["username"]
			password = form.cleaned_data["password"]
			user = authenticate(username=username, password=password)  # Nous vérifions si les données sont correctes
			print(user)

			if user:  # Si l'objet renvoyé n'est pas None
				print("ok")                
				login(request, user)  # nous connectons l'utilisateur
				return redirect(hello)
			  #return render(request, 'accueil_login/hello.html')
			else: # sinon une erreur sera affichée
				print("pasco")
				error = True
	else:
		form = ConnexionForm()

	if request.user.is_authenticated:
		return redirect(hello)

	return render(request, 'accueil_login/home.html', locals())

def apropos(request):
	return render(request, 'accueil_login/apropos.html', locals())
	
def hello(request):
	if not request.user.is_authenticated :
		return redirect(home)
	else :
		return render(request, 'accueil_login/hello.html', locals())

#def home(request):
	#return render(request, 'accueil_login/home.html')
	#return render(request, 'accueil_login/index.html')


def deconnexion(request):
	logout(request)
	return render(request, 'accueil_login/home.html', locals())


def signup(request):
	if request.method == 'POST':
		form = SignupForm(request.POST)
		if form.is_valid():
			user = form.save(commit=False)
			user.is_active = False
			user.save()
			current_site = get_current_site(request)
			mail_subject = 'Activer votre compte Stats Eisti.'
			message = render_to_string('accueil_login/acc_active_email.html', {
				'user': user,
				'domain': current_site.domain,
				'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
				'token':account_activation_token.make_token(user),
			})
			to_email = form.cleaned_data.get('email')
			email = EmailMessage(
						mail_subject, message, to=[to_email]
			)
			email.send()
			return render(request, 'accueil_login/message_inscription.html', locals())
			#return HttpResponse(tmp)
	else:
		form = SignupForm()
	return render(request, 'accueil_login/signup.html', {'form': form})

def activate(request, uidb64, token):
	try:
		uid = force_text(urlsafe_base64_decode(uidb64))
		user = User.objects.get(pk=uid)
	except(TypeError, ValueError, OverflowError, User.DoesNotExist):
		user = None
	if user is not None and account_activation_token.check_token(user, token):
		user.is_active = True
		user.save()
		login(request, user)
		# return redirect('home')
		return render(request, 'accueil_login/merci.html', locals())
	else:
		return HttpResponse("Le lien d'activation est invalide !")

accueil_login/templates/accueil_login/acc_active_email.html
{% autoescape off %}
Bonjour {{ user.username }},
Veuillez cliquer sur ce lien pour confirmer votre inscription sur Stats Eisti,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

accueil_login/templates/accueil_login/apropos.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
<head>
	<title>A propos</title>
	<link rel="stylesheet" type="text/css" href="{% static 'statistiques/CSS/index.css' %}" />
  <script src="{% static 'statistiques/JS/index.js' %}"></script>
  <link href="https://fonts.googleapis.com/css?family=Maven+Pro" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'statistiques/bootstrap/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'statistiques/CSS/STATS/stats.css' %}">
  <script src="{% static 'statistiques/bootstrap/js/jquery.js' %}"></script>
  <script src="{% static 'statistiques/bootstrap/js/bootstrap.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.js"></script>
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
   <link rel="stylesheet" href="https://openlayers.org/en/v4.6.4/css/ol.css" type="text/css">

  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css"
   integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ=="
   crossorigin=""/>
   <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"
   integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log=="
   crossorigin=""></script>


</head>

<body>

{% include 'accueil_login/menu_utilisateur.html' %}

<div class="container">
  <p class=""><h2> Qui sommes nous ?</h2></p>
  <div class="row">
    <div class="col-md dev">
     <div class="container mt-4 mb-4">
  <div class="list-group">

  <div href="#" class=" flex-column align-items-start ">
    <div class="d-flex w-100 justify-content-between">

    </div>
    <div class="card">
  <div class="card-body">
   <div class="" class="container">
  <div class="d-flex justify-content-between">
    <div class="p-1">
    </div>
    <div>

            <img id="image_file"  src="{% static 'accueil_login/images/bear.png' %}" width="50px" height="50px">


    </div>
    <div class="p-1">

    </div>
  </div>
</div>
    <p class=" mb-1 mt-2 text-center">Florin Gogibus</p>

    <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>


          </div>
          <div class="p-1">

          </div>
        </div>
  </div>
</div>

  </div>

</div>
</div>
    </div>
    <div class="col-md dev">
     <div class="container mt-4 mb-4">
  <div class="list-group">

  <div href="#" class=" flex-column align-items-start ">
    <div class="d-flex w-100 justify-content-between">

    </div>
    <div class="card">
  <div class="card-body">
   <div class="" class="container">
  <div class="d-flex justify-content-between">
    <div class="p-1">
    </div>
    <div>
        <img id="image_file"  src="{% static 'accueil_login/images/penguin.png' %}" width="50px" height="50px">


    </div>
    <div class="p-1">

    </div>
  </div>
</div>
    <p class="mb-1 mt-2 text-center">Alexandre Hassan</p>

    <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>


          </div>
          <div class="p-1">

          </div>
        </div>
  </div>
</div>

  </div>

</div>
</div>
    </div>
    <div class="col-md dev">
            <div class="container mt-4 mb-4">
        <div class="list-group">

        <div href="#" class=" flex-column align-items-start ">
          <div class="d-flex w-100 justify-content-between">

          </div>
          <div class="card">
        <div class="card-body">
         <div class="" class="container">
        <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>
              <img id="image_file"  src="{% static 'accueil_login/images/deer.png' %}" width="50px" height="50px">


          </div>
          <div class="p-1">

          </div>
        </div>
      </div>
          <p class="mb-1 mt-2 text-center">Thomas Ogier</p>

          <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>


          </div>
          <div class="p-1">

          </div>
        </div>

        </div>
      </div>

        </div>

      </div>
      </div>
    </div>
    <div class="col-md dev">
     <div class="container mt-4 mb-4">
  <div class="list-group">

  <div href="#" class=" flex-column align-items-start ">
    <div class="d-flex w-100 justify-content-between">

    </div>
    <div class="card">
  <div class="card-body">
   <div class="" class="container">
  <div class="d-flex justify-content-between">
    <div class="p-1">
    </div>
    <div>
          <img id="image_file"  src="{% static 'accueil_login/images/husky.png' %}" width="50px" height="50px">


    </div>
    <div class="p-1">

    </div>
  </div>
</div>
    <p class="mb-1 mt-2 text-center">Caroline Ung </p>

    <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>


          </div>
          <div class="p-1">

          </div>
        </div>
  </div>
</div>

  </div>

</div>
</div>
    </div>



  </div>
  <div class="row">
    <div class="col-md ap">
     <div class="container mt-4 mb-4">
  <div class="list-group">

  <div href="#" class=" flex-column align-items-start ">
    <div class="d-flex w-100 justify-content-between">

    </div>
    <div class="card">
  <div class="card-body">
   <div class="" class="container">
  <div class="d-flex justify-content-between">
    <div class="p-1">
    </div>
    <div>
          <img class="" id="image_file" src="{% static 'accueil_login/images/logo.png'%}" alt="PNG" width="150px" height="150px">


    </div>
    <div class="p-1">

    </div>
  </div>
</div>
    <p class="mb-1 text-justify mx-4">Nous sommes des étudiants en informatique à l'EISTI sur le campus de Cergy, ce projet de développement web a consisté à créer un site repondant à de nombreux critères que nous avons essayé de respecter au maximum.
    Nous avons voulu faire un site au design simple d'utilisation, compréhensible pour tous. Nous espérons que vous trouverez votre bonheur sur StatS EISTI !</p>

    <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>


          </div>
          <div class="p-1">

          </div>
        </div>
  </div>
</div>

  </div>

</div>
</div>
    </div>
  </div>
</div>


<div class="container mb-3">
   <div>
     <div class="row">
       <div class="col-md ">
         <div id="mapid" style="height: 450px; width : 70%; margin-left : 16% "></div>
       </div>
     </div>
   </div>
</div>
<script type="text/javascript">
  var mymap = L.map('mapid').setView([49.0349755, 2.0695911], 16);
L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZmxvcmlub3V6ZXJyIiwiYSI6ImNqYzk5ZjY3czBtbWkzM280empubW9rYnoifQ.PGXCsxw-kguymXs8Id0d1g', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox.streets',
    accessToken: 'your.mapbox.access.token'
}).addTo(mymap);
var marker = L.marker([49.0349755, 2.0695911]).addTo(mymap);
marker.bindPopup("<b>EISTI - Campus de Cergy</b> <i><br>Avenue du Parc<br>95011 Cergy - Pontoise</i>").openPopup();




</script>



  {% include 'accueil_login/footer.html' %}
  </body>
  </html>

accueil_login/templates/accueil_login/footer.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'accueil_login/CSS/footer.css' %}">
</head>
<footer>

     <div class="container">
       <div class="row">

                <div class="col-md-4 col-sm-6 col-xs-12">
                  <div class="container">
                    <div class="d-flex justify-content-between">
                      <div class="p-1">
                      </div>
                      <div>
                            <img src="{% static 'accueil_login/images/logo_eisti.png' %}"  style="background-color: white;" width="60px" height="80px" class="mb-3">
                  <img src="{% static 'accueil_login/images/logo.png' %}" width="80px" height="80px" class="d-inline-block align-top ml-2" alt="" style="background-color: white;">

                      </div>
                      <div class="p-1">

                      </div>
                    </div>

                  </div>
                  <p class="descriptif">Stats Eisti est un site permettant de faire des statistiques sur les élèves de l'école d'Ingénieur EISTI. </p>
                  <p class="descriptif">© 2017-2018 Stats Eisti </p>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12">
                    <ul class="menu">
                         <span>Menu</span>
                         <li>
                            <a href="{% url 'statistiques:menu_stats' %}">Statistiques</a>
                          </li>

                          <li>
                             <a href="{% url 'email' %}">Nous contacter</a>
                          </li>

                          <li>
                            <a href="{% url 'apropos' %}">A propos</a>
                          </li>
                     </ul>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12">
                  <ul class="langues">
                        <span>Langues</span>
                        <li>
                          <img src="{% static 'accueil_login/images/france.png' %}" width="25px" height="25px">
                           <i class="fa fa-phone" aria-hidden="true"></i> <a href="#">Français</a>
                        </li>
                        <li>
                          <img src="{% static 'accueil_login/images/united-kingdom.png' %}" width="25px" height="25px">
                           <i class="fa fa-map-marker" aria-hidden="true"></i> <a href="#">Anglais</a>
                        </li>
                        <li>
                          <img src="{% static 'accueil_login/images/spain.png' %}" width="25px" height="25px">
                           <i class="fa fa-envelope" aria-hidden="true"></i> <a href="#">Espagnol</a>
                        </li>
                   </ul>
               </div>


           </div>
        </div>
    </footer>

accueil_login/templates/accueil_login/hello.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Hello{% endblock %}</title>

    <script src="{% static 'importationfichier/JS/index.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Maven+Pro" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'importationfichier/bootstrap/css/bootstrap.css' %}">
    <script src="{% static 'importationfichier/bootstrap/js/jquery.js' %}"></script>
    <script src="{% static 'importationfichier/bootstrap/js/bootstrap.js' %}"></script>
    <link rel="stylesheet" href="{% static 'accueil_login/CSS/accueil.css' %}">
    <link rel="stylesheet" href="{% static 'accueil_login/CSS/footer.css' %}">

</head>
<body>

  {% include 'accueil_login/menu_utilisateur.html' %}


<div class="mt-1 mb-1" class="container">
  <div class="d-flex justify-content-between">
    <div class="p-1">
    </div>
    <div>
           <div class="container">
<br>
  <section>
<a href="{% url 'statistiques:menu_stats' %}" class="text-center"><button type="button" class="btn btn-light">
Cliquer ici pour accéder au statistiques</button></a>
  </section>
  </div>

    </div>
    <div class="p-1">
      
    </div>
  </div>
</div>

 

  <div class="container mt-3 mb-3" style="width: 75%" >
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'accueil_login/images/stats.jpg' %}" class="img-fluid" alt="Responsive image"  >
          </div>
          <div class="carousel-item">
           <img class="d-block w-100" src="{% static 'accueil_login/images/django.png' %}" class="img-fluid" alt="Responsive image">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
  </div>

  

  {% block content %}
  {% endblock %}

  {% include 'accueil_login/footer.html' %}

</body>
</html>

accueil_login/templates/accueil_login/menu_gestionnaire.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'accueil_login/CSS/accueil.css' %}">
</head>
<!--
<nav class="navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Stats Eisti</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav text-md-center nav-justified w-100">

      <li class="nav-item active">
        <a class="nav-link" href="#">Importer fichiers</a>
      </li>
      
      <li class="nav-item active dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mon compte 
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Mes informations</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'deconnexion' %}">Se déconnecter</a>
        </div>
      </li>
    </ul>
  </div>
</nav>-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <img src="{% static 'accueil_login/images/logo.png' %}" width="45" height="45" class="d-inline-block " alt="" style="background-color: white;">
  <a class="navbar-brand ml-3" href="{% url 'statistiques:menu_stats' %}" style="font-size: 17px;">
     Stats Eisti
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto text-center">
     
    </ul>
       <ul class="nav navbar-nav navbar-right text-center">

 
        <a href="{% url 'importationfichier:nouveau_document' %}"><li class="text-light mr-3" style="font-size: 17px">Importer fichiers</li></a>
        <a href="#"><li class="text-light mr-3" style="font-size: 17px">Mon compte</li></a>
        <a href="{% url 'deconnexion'%}"><li class="text-light mr-3" style="font-size: 17px">Se déconnecter</li></a>
        </ul>
  </div>
</nav>

accueil_login/templates/accueil_login/menu_utilisateur.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'accueil_login/CSS/accueil.css' %}">
</head>
<!--
<nav class="navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Stats Eisti</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav text-md-center nav-justified w-100">

      <li class="nav-item active">
        <a class="nav-link" href="#">Importer fichiers</a>
      </li>

      <li class="nav-item active dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mon compte
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Mes informations</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'deconnexion' %}">Se déconnecter</a>
        </div>
      </li>
    </ul>
  </div>
</nav>-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <img src="{% static 'accueil_login/images/logo.png' %}" width="45" height="45" class="d-inline-block " alt="" style="background-color: white;">
  <a class="navbar-brand ml-3" href="{% url 'hello' %}" style="font-size: 17px;">
     Stats Eisti
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">

    </ul>
       <ul class="nav navbar-nav navbar-right text-center">


          <a href="{% url 'profil:pageprofil'%}">  <li class="text-light mr-3" style="font-size: 17px">Mon compte</li>
            <a href="{% url 'deconnexion'%}"><li class="text-light mr-3" style="font-size: 17px">Se déconnecter</li></a>
        </ul>
  </div>
</nav>

accueil_login/templates/accueil_login/signup.html
{% extends 'accueil_login/base.html' %}

{% block content %}

{% load widget_tweaks %}
{% load static %}


  <div class="container_login">
    <div class="info">
      <h1> Logo Stats Eisti</h1>
      <p> Bienvenue sur Stats Eisti </p>
    </div>
  </div> 

  <div class="form">
    <div class="thumbnail"><img src="{% static 'accueil_login/images/create-account.png' %}"></div>
      <form method="post">
        

        <!--{% if error %}
          <div class="invalid-feedback"> {{ error }} </div>
        {% endif %}-->

        {% csrf_token %}
          
          <!--<input id="id_username" type="text" name="username" placeholder="Nom d'utilisateur" maxlength="150" autofocus required />
          <small class="form-text text-muted"> Requis. 150 caractères maximum. Uniquement des lettres, nombres et les caractères « @ », « . », « + », « - » et « _ ». </small>
    
          <input id="id_email" type="email" name="email" placeholder="Adresse e-mail" maxlength="200" required />
          <small class="form-text text-muted"> Requis.</small>

          <input id="id_password1" type="password" name="password1" placeholder="Mot de passe" required/>
          <small class="form-text text-muted text-justify"><ul><li>Votre mot de passe ne peut pas trop ressembler à vos autres informations personnelles.</li><li>Votre mot de passe doit contenir au minimum 8 caractères.</li><li>Votre mot de passe ne peut pas être un mot de passe couramment utilisé.</li><li>Votre mot de passe ne peut pas être entièrement numérique.</li></ul></small>


          <input id="id_password2" type="password" name="password2" placeholder="Confirmation du mot de passe" required/>
          <small class="form-text text-muted">Saisissez le même mot de passe que précédemment, pour vérification.</small>-->


        {% for field in form %}
          <div class="form-group">
            {{ field.label_tag }}

            {% if form.is_bound %}
              {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                  <div class="invalid-feedback">
                    {{ error }}
                  </div>
                {% endfor %}
              {% else %}
                {% render_field field class="form-control is-valid" %}
              {% endif %}
            {% else %}
              {% render_field field class="form-control" %}
            {% endif %}

            {% if field.help_text %}
              <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
          </div>
        {% endfor %}

        <button type="submit">Créer un compte</button>

        <p class="message">Déjà inscrit? <a href="{% url 'home' %}">Se connecter</a></p>
      </form> 
  </div>

{% endblock %}