nous_contacter/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from nous_contacter import views

#app_name = 'nous_contacter'
#urlpatterns = [
#	url(r'^contact$', views.contact, name='contact'),
#]


# sendemail/urls.py
urlpatterns = [
	url(r'^email/$', views.emailView, name='email'),
	url(r'^success/$', views.successView, name='success'),
    #path('email/', views.emailView, name='email'),
    #path('success/', views.successView, name='success'),
]

stats/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
	path('nous_contacter/', include('nous_contacter.urls')),
    path('accueil_login/', include('accueil_login.urls')),
    #path('importationfichier/', include('importationfichier.urls')),
    path('backoffice/', include('backoffice.urls')),
    path('admin/', admin.site.urls),
    path('statistiques/', include('statistiques.urls')),
    path('importationfichier/', include('importationfichier.urls',namespace='importationfichier')),
	path('profil/', include('profil.urls')),
]

backoffice/models.py
from django.db import models


class Accede(models.Model):
    idutilisateur = models.ForeignKey('Utilisateur', models.DO_NOTHING, db_column='idUtilisateur', primary_key=True)  # Field name made lowercase.
    idfonction = models.ForeignKey('Fonction', models.DO_NOTHING, db_column='idFonction')  # Field name made lowercase.



class Connexion(models.Model):
    adresseip = models.CharField(db_column='adresseIP', max_length=16, blank=True, null=True)  # Field name made lowercase.
    systexploitation = models.CharField(db_column='systExploitation', max_length=50, blank=True, null=True)  # Field name made lowercase.
    datedebut = models.DateTimeField(db_column='dateDebut', blank=True, null=True)  # Field name made lowercase.
    duree = models.TimeField(blank=True, null=True)
    idutilisateur = models.ForeignKey('Utilisateur', models.DO_NOTHING, db_column='idUtilisateur', blank=True, null=True)  # Field name made lowercase.



class Eleve(models.Model):
    id = models.CharField(primary_key=True, max_length=15)
    adresse = models.CharField(max_length=100, blank=True, null=True)
    codepostal = models.CharField(db_column='codePostal', max_length=10, blank=True, null=True)  # Field name made lowercase.
    ville = models.CharField(max_length=50, blank=True, null=True)
    pays = models.CharField(max_length=50, blank=True, null=True)
    longitude = models.CharField(max_length=50, blank=True, null=True)
    latitude = models.CharField(max_length=50, blank=True, null=True)
    longitude = models.CharField(max_length=50,null=True)
    latitude = models.CharField(max_length=50,null=True)

class Fonction(models.Model):
    libelle = models.CharField(max_length=20, blank=True, null=True)

    

class Specialitecampus(models.Model):
    programme = models.CharField(max_length=20, blank=True, null=True)
    campus = models.CharField(max_length=25, blank=True, null=True)
    anneescolaire = models.CharField(db_column='anneeScolaire', max_length=9, blank=True, null=True)  # Field name made lowercase.
    ideleve = models.ForeignKey(Eleve, models.DO_NOTHING, db_column='idEleve', blank=True, null=True)  # Field name made lowercase.



class Stage(models.Model):
    annee = models.CharField(max_length=150, blank=True, null=True)
    anneescolaire = models.CharField(db_column='anneeScolaire', max_length=20, blank=True, null=True)  # Field name made lowercase.
    entreprise = models.CharField(max_length=100, blank=True, null=True)
    codepostal = models.CharField(db_column='codePostal', max_length=25, blank=True, null=True)  # Field name made lowercase.
    ville = models.CharField(max_length=50, blank=True, null=True)
    pays = models.CharField(max_length=50, blank=True, null=True)
    sujet = models.CharField(max_length=3000, blank=True, null=True)
    salaire = models.CharField(max_length=10,blank=True, null=True)
    ideleve = models.ForeignKey(Eleve, models.DO_NOTHING, db_column='idEleve', blank=True, null=True)  # Field name made lowercase.
    longitude = models.CharField(max_length=50, blank=True, null=True)
    latitude = models.CharField(max_length=50, blank=True, null=True)



class Pays(models.Model):
    pays = models.CharField(max_length=50, blank=True, null=True)
    longitude = models.CharField(max_length=50, blank=True, null=True)
    latitude = models.CharField(max_length=50, blank=True, null=True)




class Utilisateur(models.Model):
    nom = models.CharField(max_length=50, blank=True, null=True)
    prenom = models.CharField(max_length=100, blank=True, null=True)
    mail = models.CharField(max_length=100, blank=True, null=True)
    motdepasse = models.CharField(db_column='motDePasse', max_length=50, blank=True, null=True)  # Field name made lowercase.
    adresse = models.CharField(max_length=100, blank=True, null=True)
    codepostal = models.CharField(db_column='codePostal', max_length=10, blank=True, null=True)  # Field name made lowercase.
    ville = models.CharField(max_length=100, blank=True, null=True)
    pays = models.CharField(max_length=50, blank=True, null=True)
    telephone = models.CharField(max_length=10, blank=True, null=True)

nous_contacter/models.py
from django.db import models

# Create your models here.

nous_contacter/forms.py
from django import forms

#class ContactForm(forms.Form):
#	subject = forms.CharField(max_length=100)
#	envoyeur = forms.EmailField(label="Votre adresse e-mail")
#	message = forms.CharField(widget=forms.Textarea)
#	renvoi = forms.BooleanField(help_text="Cochez si vous souhaitez obtenir une copie du mail envoyé.", required=False)


#https://openclassrooms.com/courses/developpez-votre-site-web-avec-le-framework-django/les-formulaires-6


# sendemail/forms.py
class ContactForm(forms.Form):
	subject = forms.CharField(label="Sujet",max_length=100,required=True)
	from_email = forms.EmailField(label="Adresse e-mail",required=True)
	message = forms.CharField(label="Message",widget=forms.Textarea, required=True)

nous_contacter/views.py
#from django.shortcuts import render
#from .forms import ContactForm

#def contact(request):
	# Construire le formulaire, soit avec les données postées,
	# soit vide si l'utilisateur accède pour la première fois
	# à la page.
#	form = ContactForm(request.POST or None)
	# Nous vérifions que les données envoyées sont valides
	# Cette méthode renvoie False s'il n'y a pas de données 
	# dans le formulaire ou qu'il contient des erreurs.
#	if form.is_valid():
		# Ici nous pouvons traiter les données du formulaire
#		suject = form.cleaned_data['subject']
#		message = form.cleaned_data['message']
#		envoyeur = form.cleaned_data['envoyeur']
#		renvoi = form.cleaned_data['renvoi']

		# Nous pourrions ici envoyer l'e-mail grâce aux données 
		# que nous venons de récupérer
#		envoi = True
	
	# Quoiqu'il arrive, on affiche la page du formulaire.
#	return render(request, 'nous_contacter/contact.html', locals())


# sendemail/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm

def emailView(request):
	if request.method == 'GET':
		form = ContactForm()
	else:
		form = ContactForm(request.POST)
		if form.is_valid():
			subject = form.cleaned_data['subject']
			from_email = form.cleaned_data['from_email']
			message = form.cleaned_data['message']
			try:
				send_mail(subject, message, from_email, ['florin.gogibus78100@gmail.com']) #Le mail sera envoyé à florin.gogibus78100@gmail.com
			except BadHeaderError:
				return HttpResponse('Invalid header found.')
			return redirect(successView)
	return render(request, "nous_contacter/email.html", {'form': form})

def successView(request):
   return HttpResponse('Success! Thank you for your message.')

nous_contacter/templates/nous_contacter/contact.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Nous contacter</title>
  <!-- UIkit CSS -->
   <!--<link rel="stylesheet" type="text/css" href="{% static 'importationfichier/CSS/uikit.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'importationfichier/CSS/index.css' %}" />
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> 

  <script src="{% static 'importationfichier/JS/uikit.min.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.35/js/uikit-icons.min.js"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
 
  <script src="{% static 'importationfichier/JS/uikit-icons.min.js' %}"></script>
    -->
  <script src="{% static 'importationfichier/JS/index.js' %}"></script>
  <link href="https://fonts.googleapis.com/css?family=Maven+Pro" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'importationfichier/bootstrap/css/bootstrap.css' %}">
  <script src="{% static 'importationfichier/bootstrap/js/jquery.js' %}"></script>
  <script src="{% static 'importationfichier/bootstrap/js/bootstrap.js' %}"></script>
  <link rel="stylesheet" href="{% static 'accueil_login/CSS/accueil.css' %}">
  <link rel="stylesheet" href="{% static 'accueil_login/CSS/footer.css' %}">
  <link rel="stylesheet" href="{% static 'nous_contacter/CSS/contact.css' %}">

  </head>

  <body>

  <!-- Inclusion de la barre de menu -->
  {% block content %}
    {% include 'accueil_login/menu_utilisateur.html' %}

  
  {% if envoi %}
    <div class="alert alert-success" role="alert">
      Votre message a bien été envoyé !
    </div>
  {% endif %}  
  
  <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="well well-sm">
            <form class="form-horizontal" action="" method="post">
            <fieldset>
              <legend class="text-center">Nous contacter</legend>
              <hr>

              {% csrf_token %}

              <!-- Subject input-->
              <div class="form-group">
                <label class="col-md-3 control-label" for="id_sujet">Sujet</label>
                <div class="col-md-9">
                  <input id="id_sujet" name="sujet" type="text" placeholder="Votre sujet" class="form-control" maxlength="100">
                </div>
              </div>
      
              <!-- Email input-->
              <div class="form-group">
                <label class="col-md-3 control-label" for="id_envoyeur">E-mail</label>
                <div class="col-md-9">
                  <input id="id_envoyeur" name="envoyeur" type="text" placeholder="Votre e-mail" class="form-control">
                </div>
              </div>
      
              <!-- Message body -->
              <div class="form-group">
                <label class="col-md-3 control-label" for="id_message">Message</label>
                <div class="col-md-9">
                  <textarea class="form-control" id="id_message" name="message" placeholder="Veuillez entrer votre message ici ..." rows="5"></textarea>
                </div>
              </div>

              <!-- Case à cocher -->
              <p><input type="checkbox" name="renvoi" id="id_renvoi" /> <span class="helptext">Cochez si vous souhaitez obtenir une copie du mail envoyé.</span></p>
      
              <!-- Form actions -->
              <div class="form-group">
                <div class="col-md-12 text-right">
                  <button type="submit" class="btn btn-primary btn-lg">Envoyer</button>
                </div>
              </div>
            </fieldset>
            </form>
          </div>
        </div>
    </div>
  </div>


  <div class="container">
  <div class="row">
    <div class="col-md-4">
      <h3>Où sommes-nous ?</h3>
      
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2646.2531389455903!2d-89.23024619999998!3d48.4516724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4d5923dbfe697737%3A0xc9d925c9bc9573fa!2s116+Bruce+St%2C+Thunder+Bay%2C+ON+P7A+5W6!5e0!3m2!1sen!2sca!4v1424272264157" frameborder="0" style="border:0"></iframe>
      </div></div></div>

  <!-- Inclusion du footer -->
    {% include 'accueil_login/footer.html' %}
  {% endblock %}


</body>
</html>
    
    

nous_contacter/templates/nous_contacter/email.html
{% load widget_tweaks %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>Nous contacter</title>
  <!-- UIkit CSS -->
   <!--<link rel="stylesheet" type="text/css" href="{% static 'importationfichier/CSS/uikit.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'importationfichier/CSS/index.css' %}" />
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> 

  <script src="{% static 'importationfichier/JS/uikit.min.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.35/js/uikit-icons.min.js"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
 
  <script src="{% static 'importationfichier/JS/uikit-icons.min.js' %}"></script>
    -->
  <script src="{% static 'importationfichier/JS/index.js' %}"></script>
  <link href="https://fonts.googleapis.com/css?family=Maven+Pro" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'importationfichier/bootstrap/css/bootstrap.css' %}">
  <script src="{% static 'importationfichier/bootstrap/js/jquery.js' %}"></script>
  <script src="{% static 'importationfichier/bootstrap/js/bootstrap.js' %}"></script>
  <link rel="stylesheet" href="{% static 'accueil_login/CSS/accueil.css' %}">
  <link rel="stylesheet" href="{% static 'accueil_login/CSS/footer.css' %}">
  <link rel="stylesheet" href="{% static 'nous_contacter/CSS/contact.css' %}">

  </head>

  <body>

    {% include 'accueil_login/menu_utilisateur.html' %}


	<div class="mt-4 mb-4" class="container">
	  <div class="d-flex justify-content-between">
	    <div class="p-1">
	    </div>
	    <div class="card mt-4 mb-4 px-5 py-4 bg-light">
	        <h1 class="mb-4 text-center">Nous contacter</h1>
				<form method="post">

				    {% csrf_token %}
				    <!--{{ form.as_p }}-->
				    {% render_field form.subject class="form-control mb-4" placeholder="Sujet" %}
				    {% render_field form.from_email class="form-control mb-4" placeholder="E-mail" %}
				    {% render_field form.message class="form-control mb-4" placeholder="Message" %}

					<div class="form-actions text-center">
				      <button type="submit" class="btn btn-primary">Envoyer</button>
				    </div>
	    </div>
	    <div class="p-1">
	      
	    </div>
	  </div>
	</div>


  <!--<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h3>Où sommes-nous ?</h3>
      
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2646.2531389455903!2d-89.23024619999998!3d48.4516724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4d5923dbfe697737%3A0xc9d925c9bc9573fa!2s116+Bruce+St%2C+Thunder+Bay%2C+ON+P7A+5W6!5e0!3m2!1sen!2sca!4v1424272264157" frameborder="0" style="border:0"></iframe>
      </div></div></div>
	-->

    {% include 'accueil_login/footer.html' %}

</body>
</html>
    
    

nous_contacter/templates/nous_contacter/succes.html
<h1>Success! Email sent.</h1>