statistiques/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from statistiques import views

app_name = 'statistiques'
urlpatterns = [
	url(r'^menu_stats$', views.menu_stats, name='menu_stats'),
	url(r'^uni_programme$', views.uni_programme, name='uni_programme'),
	url(r'^quali_quali$',views.quali_quali, name ='quali_quali'),
	url(r'^uni_eleves$',views.uni_eleves, name ='uni_eleves'),
	url(r'^result$',views.result, name ='result'),
	url(r'^money_stage$',views.money_stage, name ='money_stage'),
	url(r'^best_stage$',views.best_stage, name ='best_stage'),

]

stats/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
	path('nous_contacter/', include('nous_contacter.urls')),
    path('accueil_login/', include('accueil_login.urls')),
    #path('importationfichier/', include('importationfichier.urls')),
    path('backoffice/', include('backoffice.urls')),
    path('admin/', admin.site.urls),
    path('statistiques/', include('statistiques.urls')),
    path('importationfichier/', include('importationfichier.urls',namespace='importationfichier')),
	path('profil/', include('profil.urls')),
]

statistiques/models.py
from django.db import models

# Create your models here.

statistiques/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, Group
from backoffice.models import *
from accueil_login.views import home

import json
import itertools
import random
import os
import csv

# Create your views here.

def hex_code_colors(): #fontion qui permet de creer des couleurs aléatoirement
    a = hex(random.randrange(0,256))
    b = hex(random.randrange(0,256))
    c = hex(random.randrange(0,256))
    a = a[2:]
    b = b[2:]
    c = c[2:]
    if len(a)<2:
        a = "0" + a
    if len(b)<2:
        b = "0" + b
    if len(c)<2:
        c = "0" + c
    z = a + b + c
    return "#" + z.upper()


def menu_stats(request):
    if request.user.is_active:
        return render(request, 'statistiques/index.html')
    else :
        return redirect(home)   



def uni_programme(request):
    if request.user.is_active:
        donnees_campus = []
        donnees_annee_scolaire = []
        color_campus = []
        color_annee_scolaire = []
        labels_campus = []
        labels_annee_scolaire = []
        val_list_campus = []
        val_list_annee_scolaire = []
        val_list_programme= []
        val_int_campus = []
        val_int_annee_scolaire = []

        labels_bdd_campus = Specialitecampus.objects.values('campus').distinct()
        labels_bdd_annee_scolaire = Specialitecampus.objects.values('anneescolaire').distinct().order_by('anneescolaire')   

    
        for tmp in labels_bdd_campus:
            labels_campus.append(tmp['campus'].replace("\n",""))
            val_int_campus.append(Specialitecampus.objects.filter(campus = tmp['campus']).values('ideleve').distinct().count())
            color_campus.append(hex_code_colors())

        for tmp in labels_bdd_annee_scolaire:
            labels_annee_scolaire.append(tmp['anneescolaire'].replace("\n",""))
            val_int_annee_scolaire.append(Specialitecampus.objects.filter(anneescolaire = tmp['anneescolaire']).values('ideleve').distinct().count())
            color_annee_scolaire.append(hex_code_colors())

        somme_campus = sum(val_int_campus)
        
        for tmp in val_int_campus:
            donnees_campus.append(round(tmp / somme_campus,2)*100)

        for tmp in val_int_annee_scolaire:
            donnees_annee_scolaire.append(tmp)

        for tmp,tmp_bis in zip(labels_campus,val_int_campus):
            val_list_campus.append("Nombre d'élève à " + tmp + " : " + str(tmp_bis))

        

        donnees_campus.append(0)
        donnees_annee_scolaire.append(0)

        return render(request, 'statistiques/uni_programme.html',{
            'total_cergy' : val_list_campus[0],
            'total_pau' : val_list_campus[1],
            'donnees_campus':donnees_campus,
            'donnees_annee_scolaire' : donnees_annee_scolaire,
            'labels_campus' : labels_campus,
            'labels_annee_scolaire' : labels_annee_scolaire,
            'total_eleve' : somme_campus,
            'var_list_campus':val_list_campus,
            'var_list_annee_scolaire' : val_list_annee_scolaire,
            'color_campus' : color_campus,
            'color_annee_scolaire' : color_annee_scolaire,
            'labels_annee_scolaire' : labels_annee_scolaire,})
        return redirect(home)
    else :
        return redirect(home)   

def quali_quali(request) :
    if request.user.is_active:
        color_programme_ING = []
        color_programme_CPI = []
        labels_annee_scolaire = []
        labels_programme_ING = []
        labels_programme_CPI = []
        labels_annee_scolaire = []
        val_list_annee_scolaire = []
        val_list_programme= []
        val_int_campus = []
        val_int_annee_scolaire = []
        val_int_programme_ING = []
        val_int_programme_CPI = []

        labels_bdd_annee_scolaire = Specialitecampus.objects.values('anneescolaire').distinct().order_by('anneescolaire')   
        labels_bdd_programme_ING = (Specialitecampus.objects.filter(programme__startswith='ING')).values('programme').distinct().order_by('programme')
        labels_bdd_programme_CPI = (Specialitecampus.objects.filter(programme__startswith='CPI')).values('programme').distinct().order_by('programme')

        for annee in labels_bdd_annee_scolaire:
            labels_annee_scolaire.append(annee['anneescolaire'].replace("\n",""))


        for prog in labels_bdd_programme_ING:
            labels_programme_ING.append(prog['programme'].replace("\n",""))

        for prog in labels_bdd_programme_CPI:
            labels_programme_CPI.append(prog['programme'].replace("\n",""))

        for tmp in labels_bdd_annee_scolaire:
            tmp_valeur = []
            tmp_couleur = []
            for prog in labels_bdd_programme_ING:
                tmp_valeur.append((Specialitecampus.objects.filter(programme = prog['programme']) & Specialitecampus.objects.filter(anneescolaire = tmp['anneescolaire'])).values('ideleve').distinct().count())
                tmp_couleur.append(hex_code_colors())
            val_int_programme_ING.append(tmp_valeur)
            color_programme_ING.append(tmp_couleur)

        for tmp in labels_bdd_annee_scolaire:
            tmp_valeur = []
            tmp_couleur = []
            for prog in labels_bdd_programme_CPI:
                tmp_valeur.append((Specialitecampus.objects.filter(programme = prog['programme']) & Specialitecampus.objects.filter(anneescolaire = tmp['anneescolaire'])).values('ideleve').distinct().count())
                tmp_couleur.append(hex_code_colors())
            val_int_programme_CPI.append(tmp_valeur)
            color_programme_CPI.append(tmp_couleur)
        


        liste_ING = zip(val_int_programme_ING,color_programme_ING)
        liste_CPI = zip(val_int_programme_CPI,color_programme_CPI)
        return render(request, 'statistiques/quali_quali.html',{
            'labels_annee_scolaire' : labels_annee_scolaire,
            'labels_programme_ING' :labels_programme_ING,
            'labels_programme_CPI' : labels_programme_CPI,
            'liste_ING':liste_ING,
            'liste_CPI': liste_CPI})
        return redirect(home)
    else :
        return redirect(home)   

def uni_eleves(request) :
    if request.user.is_active:
        i = 0
        val_int_pays = []
        labels_pays = []
        pays_gps = []
        color_pays = []
        labels_pays_trunc = []
        val_int_pays_trunc = []
        val_int_pays_tmp = []
        labels_bdd_pays = Eleve.objects.values('pays').distinct()
        labels_bdd_ville = Eleve.objects.values('ville').distinct().order_by('vile')    


        oss_lon = []
        oss_lat = []
        tmp = os.getcwd() +"/media/documents/geo_adr.txt.geocoded.csv"
        cr = csv.reader(open(tmp,'r'),delimiter=',')
        for f in cr:
            try :
                oss_lat.append(float(f[0]))
                oss_lon.append(float(f[1]))
                print(i)
                i = i +1
            except:
                i = i + 0


        i = 0

        for tmp in labels_bdd_pays:
            labels_pays.append(tmp['pays'].replace("\n",""))
            
            val_int_pays.append(Eleve.objects.filter(pays = tmp['pays']).values('id').distinct().count())
            color_pays.append(hex_code_colors())

        val_int_pays_tmp = sorted(zip(val_int_pays, range(len(val_int_pays))),reverse = True)
        print(val_int_pays_tmp)
        for val in val_int_pays_tmp: 
            labels_pays_trunc.append(labels_pays[val_int_pays_tmp[i][1]])
            if (tmp != None):
                print("111")
            val_int_pays_trunc.append(val_int_pays_tmp[i][0])
            i = i +1
        val_int_pays.append(0)
        return render(request, 'statistiques/uni_eleves.html',{
            'labels_pays' : labels_pays_trunc,
            'val_int_pays' : val_int_pays_trunc,
            'color_pays' : color_pays,
            'oss_lat' : oss_lat,
            'oss_lon' : oss_lon
            })
        return redirect(home)
    else :
        return redirect(home)   

def calculdistance(point1,point2):
    return(vincenty(point1, point2).miles*1.60934)

def result(request):
    if request.user.is_active:
        return render(request, 'statistiques/results.html')
    else :
        return redirect(home)   

def money_stage(request):
    i = 0
    if request.user.is_active:
        val_bdd_ing1 = []
        bdd_ing1 = Stage.objects.filter(annee='ING1')
        val_bdd_ing2 = []
        bdd_ing2 = Stage.objects.filter(annee='ING2')
        val_bdd_ing3 = []
        bdd_ing3 = Stage.objects.filter(annee='ING3')


        for x in bdd_ing1:
            try :
                val_bdd_ing1.append(float(x.salaire.replace(',','.')))
            except:
                i = i +1
        salaire_ing1 = sum(val_bdd_ing1) / len(val_bdd_ing1)

        for x in bdd_ing2:
            try :
                val_bdd_ing2.append(float(x.salaire.replace(',','.')))
            except:
                i = i +1
        salaire_ing2 = sum(val_bdd_ing2) / len(val_bdd_ing2)

        for x in bdd_ing3:
            try :
                val_bdd_ing3.append(float(x.salaire.replace(',','.')))
            except:
                i = i +1
        salaire_ing3 = sum(val_bdd_ing3) / len(val_bdd_ing3)
        return render(request, 'statistiques/money_stage.html',{
            'salaire_ing1' :round(salaire_ing1,2),
            'salaire_ing2' :round(salaire_ing2,2),
            'salaire_ing3' :round(salaire_ing3,2)})
    else :
        return redirect(home)


def best_stage(request):
    i = 0
    if request.user.is_active:
        """
        labels_entreprise_trunc = []
        bdd_stage = Stage.objects.values('entreprise').distinct()
        val_int_entreprise = []
        label_stage = []
        labels_entreprise = []
        val_int_entreprise_tmp = []
        for x in bdd_stage:
            label_stage.append(x)
    
        
        for tmp in label_stage:
            labels_entreprise.append(tmp['entreprise'])
        
        for x in labels_entreprise:

statistiques/templates/statistiques/index.html
{% load static%}

<!DOCTYPE html>
<html>
<head>
	<title>Statistiques</title>
	<link rel="stylesheet" type="text/css" href="{% static 'statistiques/CSS/index.css' %}" />
  <script src="{% static 'statistiques/JS/index.js' %}"></script>
  <link href="https://fonts.googleapis.com/css?family=Maven+Pro" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'statistiques/bootstrap/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'statistiques/CSS/STATS/stats.css' %}">
  <script src="{% static 'statistiques/bootstrap/js/jquery.js' %}"></script>
  <script src="{% static 'statistiques/bootstrap/js/bootstrap.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.js"></script>


</head>
<body>
	
    {% include 'accueil_login/menu_utilisateur.html' %}


<div class="text-center">
        <h2 class="mt-4 ">Statistiques sur les élèves</h2>
</div>

<div class="container">
  <div class="row">
    <div class="col-md">
     <div class="container mt-4 mb-4">
  <div class="list-group">
    
  <div href="#" class=" flex-column align-items-start ">
    <div class="d-flex w-100 justify-content-between">
      
    </div>
    <div class="card">
  <div class="card-body">
   <div class="" class="container">
  <div class="d-flex justify-content-between">
    <div class="p-1">
    </div>
    <div>
          <img class="" id="image_file" src="{% static 'statistiques/IMAGES/progress.png'%}" alt="PNG" width="100px" height="100px">
          

    </div>
    <div class="p-1">
      
    </div>
  </div>
</div>
    <p class="mb-1 mt-2 text-center">Statistiques sur les élèves, comme leurs pays de provenances mais également les villes. Mais égalament la possibilité de voirs les résultats sur des cartes.</p>

    <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>
                <section><a href="{% url 'statistiques:uni_eleves' %}" class="text-center"><button type="button" class="btn btn-light" style="font-size: 12px;"> Cliquer ici pour accéder au statistiques</button></a>
                </section>

          </div>
          <div class="p-1">
            
          </div>
        </div>
  </div>
</div>
    
  </div>
  
</div>
</div>
    </div>
    <div class="col-md">
            <div class="container mt-4 mb-4">
        <div class="list-group">
          
        <div href="#" class=" flex-column align-items-start ">
          <div class="d-flex w-100 justify-content-between">
            
          </div>
          <div class="card">
        <div class="card-body">
         <div class="" class="container">
        <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>
                <img class="" id="image_file" src="{% static 'statistiques/IMAGES/pau.png'%}" alt="PNG" width="100px" height="100px">
                <img class="" id="image_file" src="{% static 'statistiques/IMAGES/cergy.png'%}" alt="PNG" width="100px" height="100px">
                

          </div>
          <div class="p-1">
            
          </div>
        </div>
      </div>
          <p class="mb-1 mt-2 text-center">Statistiques sur les élèves, le nombre d'élèves dans les deux campus de l'Eisti, mais également le nombre d'élèves par année scolaire tout campus confondus.</p>

          <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>
                <section><a href="{% url 'statistiques:uni_programme' %}" class="text-center"><button type="button" class="btn btn-light btn-lg" style="font-size: 12px"> Cliquer ici pour accéder au statistiques</button></a>
                </section>

          </div>
          <div class="p-1">
            
          </div>
        </div>
          
        </div>
      </div>
          
        </div>
        
      </div>
      </div>
    </div>
    <div class="col-md">
     <div class="container mt-4 mb-4">
  <div class="list-group">
    
  <div href="#" class=" flex-column align-items-start ">
    <div class="d-flex w-100 justify-content-between">
      
    </div>
    <div class="card">
  <div class="card-body">
   <div class="" class="container">
  <div class="d-flex justify-content-between">
    <div class="p-1">
    </div>
    <div>
          <img class="" id="image_file" src="{% static 'statistiques/IMAGES/quali.png'%}" alt="PNG" width="100px" height="100px">
          

    </div>
    <div class="p-1">
      
    </div>
  </div>
</div>
    <p class="mb-1 mt-2 text-center">Statistiques sur les élèves, comme le nombre d'élèves dans les programmes en fonction de l'année scolaire.</p>

    <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div class="mt-4 ">
                <section class=""><a href="{% url 'statistiques:quali_quali' %}" class="text-center "><button type="button" class="btn btn-light btn-lg " style="font-size: 12px"> Cliquer ici pour accéder au statistiques</button></a>
                </section>

          </div>
          <div class="p-1">
            
          </div>
        </div>
  </div>
</div>
    
  </div>
  
</div>
</div>
    </div>
  </div>
</div>


<div class="text-center">
        <h2 class="mt-4 ">Statistiques sur les programmes</h2>
</div>

<div class="container">
  <div class="row">
    <div class="col-md">
     <div class="container mt-4 mb-4">
  <div class="list-group">
    
  <div href="#" class=" flex-column align-items-start ">
    <div class="d-flex w-100 justify-content-between">
      
    </div>
    <div class="card">
  <div class="card-body">
   <div class="" class="container">
  <div class="d-flex justify-content-between">
    <div class="p-1">
    </div>
    <div>
          <img class="" id="image_file" src="{% static 'statistiques/IMAGES/coins.png'%}" alt="PNG" width="100px" height="100px">
          

    </div>
    <div class="p-1">
      
    </div>
  </div>
</div>
    <p class="mb-1 mt-2 text-center">Statistiques sur les programmes, comme le salaire moyen pour un stage en ING1, ING2 et ING3.</p>

    <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>
                <section><a href="{% url 'statistiques:money_stage' %}" class="text-center"><button type="button" class="btn btn-light btn-lg" style="font-size: 12px"> Cliquer ici pour accéder au statistiques</button></a>
                </section>

          </div>
          <div class="p-1">
            
          </div>
        </div>
  </div>
</div>
    
  </div>
  
</div>
</div>
    </div>
    <div class="col-md">
            <div class="container mt-4 mb-4">
        <div class="list-group">
          
        <div href="#" class=" flex-column align-items-start ">
          <div class="d-flex w-100 justify-content-between">
            
          </div>
          <div class="card">
        <div class="card-body">
         <div class="" class="container">
        <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>
                <img class="" id="image_file" src="{% static 'statistiques/IMAGES/stage.png'%}" alt="PNG" width="100px" height="100px">
                

          </div>
          <div class="p-1">
            
          </div>
        </div>
      </div>
          <p class="mb-1 mt-2 text-center">Statistiques sur les programmes, quels sont les entreprises qui embauchent le mieux.</p>

          <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>
                <section><a href="{% url 'statistiques:best_stage' %}" class="text-center"><button type="button" class="btn btn-light btn-lg" style="font-size: 12px"> Cliquer ici pour accéder au statistiques</button></a>
                </section>

          </div>
          <div class="p-1">
            
          </div>
        </div>
          
        </div>
      </div>
          
        </div>
        
      </div>
      </div>
    </div>
    
  </div>
</div>





    {% include 'accueil_login/footer.html' %}



</body>
</html>

statistiques/templates/statistiques/money_stage.html
{% load static%}

<!DOCTYPE html>
<html>
<head>
	<title>Statistiques</title>

	<link rel="stylesheet" type="text/css" href="{% static 'statistiques/CSS/index.css' %}" />
  <link href="https://fonts.googleapis.com/css?family=Maven+Pro" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'statistiques/bootstrap/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'statistiques/CSS/STATS/stats.css' %}">
  <script src="{% static 'statistiques/bootstrap/js/jquery.js' %}"></script>
  <script src="{% static 'statistiques/bootstrap/js/bootstrap.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.js"></script>




</head>
<style type="text/css">
  body {
    font-family: "Lato", sans-serif;
    transition: background-color .5s;
}


</style>
<body>

  {% include 'accueil_login/menu_utilisateur.html' %}
  <!--
	<nav class="navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Stats Eisti</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav text-md-center nav-justified w-100">
      
      
      <li class="nav-item active">
        <a class="nav-link" href="#">Importer fichiers</a>
      </li>
      
      
      <li class="nav-item active dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mon compte 
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Mes informations</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'deconnexion' %}">Se déconnecter</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
-->
<!-- MENU -->


<!-- MENU 1 -->



<div class="container mt-3" style="width: auto;">
  <nav aria-label="breadcrumb ">
  <ol class="breadcrumb " style=" background-color: #f8fbff; font-size: 13px">
    <li class="breadcrumb-item text text-center"><a href="menu_stats">Menu statistiques</a></li>
    <li class="breadcrumb-item active text-center" aria-current="page">Salaire moyen en ingénieur </li>
  </ol>
</nav>

</div>

<div class="container">
  <div class="row">
    <div class="col-md">
     <div class="container mt-4 mb-4">
  <div class="list-group">
    
  <div href="#" class=" flex-column align-items-start ">
    <div class="d-flex w-100 justify-content-between">
      
    </div>
    <div class="card">
  <div class="card-body">
   <div class="" class="container">
  <div class="d-flex justify-content-between">
    <div class="p-1">
    </div>
    <div>
          <img class="" id="image_file" src="{% static 'statistiques/IMAGES/ing1.png'%}" alt="PNG" width="100px" height="100px">
          

    </div>
    <div class="p-1">
      
    </div>
  </div>
</div>
  <h3 class="text-center mt-2">ING1</h3>
    <p class="mb-1 mt-2 text-center">Salaire moyen d'un stage d'un élève-ingénieur en 1ère année à l'EISTI  </p>
    <p class="text-center mt-2"> {{salaire_ing1}} €</p>
    <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>
                <section><a href="{% url 'statistiques:uni_eleves' %}" class="text-center"><button type="button" class="btn btn-light btn-lg" style="font-size: 12px"> Cliquer ici pour accéder au statistiques</button></a>
                </section>

          </div>
          <div class="p-1">
            
          </div>
        </div>
  </div>
</div>
    
  </div>
  
</div>
</div>
    </div>
    <div class="col-md">
            <div class="container mt-4 mb-4">
        <div class="list-group">
          
        <div href="#" class=" flex-column align-items-start ">
          <div class="d-flex w-100 justify-content-between">
            
          </div>
          <div class="card">
        <div class="card-body">
         <div class="" class="container">
        <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>
                <img class="" id="image_file" src="{% static 'statistiques/IMAGES/ing2.png'%}" alt="PNG" width="100px" height="100px">
                

          </div>
          <div class="p-1">
            
          </div>
        </div>
      </div>
          <h3 class="text-center mt-2">ING2</h3>
            <p class="mb-1 mt-2 text-center">Salaire moyen d'un stage d'un élève-ingénieur en 2ème année à l'EISTI  </p>
            <p class="text-center mt-2"> {{salaire_ing2}} €</p>
          <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div>
                <section><a href="{% url 'statistiques:uni_programme' %}" class="text-center"><button type="button" class="btn btn-light btn-lg" style="font-size: 12px"> Cliquer ici pour accéder au statistiques</button></a>
                </section>

          </div>
          <div class="p-1">
            
          </div>
        </div>
          
        </div>
      </div>
          
        </div>
        
      </div>
      </div>
    </div>
    <div class="col-md">
     <div class="container mt-4 mb-4">
  <div class="list-group">
    
  <div href="#" class=" flex-column align-items-start ">
    <div class="d-flex w-100 justify-content-between">
      
    </div>
    <div class="card">
  <div class="card-body">
   <div class="" class="container">
  <div class="d-flex justify-content-between">
    <div class="p-1">
    </div>
    <div>
          <img class="" id="image_file" src="{% static 'statistiques/IMAGES/ing3.png'%}" alt="PNG" width="100px" height="100px">
          

    </div>
    <div class="p-1">
      
    </div>
  </div>
</div>
  <h3 class="text-center mt-2">ING3</h3>
        <p class="mb-1 mt-2 text-center">Salaire moyen d'un stage d'un élève-ingénieur en 3ème année à l'EISTI  </p>
        <p class="text-center mt-2"> {{salaire_ing3}} €</p>
    <div class="d-flex justify-content-between">
          <div class="p-1">
          </div>
          <div class=" ">
                <section class=""><a href="{% url 'statistiques:quali_quali' %}" class="text-center "><button type="button" class="btn btn-light btn-lg " style="font-size: 12px"> Cliquer ici pour accéder au statistiques</button></a>
                </section>

          </div>
          <div class="p-1">
            
          </div>
        </div>
  </div>
</div>
    
  </div>
  
</div>
</div>
    </div>
  </div>
</div>



</body>
</html>